import type { Metadata } from "next";
// import { DM_Sans, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { DM_Sans } from "next/font/google";

// If loading a variable font, you don't need to specify the font weight
const dmSans = DM_Sans({ subsets: ["latin"] });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "ChainFundIt - Save Mariam from Cancer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dmSans.className}>{children}</body>
    </html>
  );
}
